// sites.js (generated by editor.html)
window.SITEBOOK = {
  "homeSections": [
    {
      "label": "(top)",
      "items": [
        "granta",
        "the-baffler",
        "spam-plaza",
        "tank",
        "nplusone",
        "cabinet",
        "lrb-blog",
        "lrb",
        "lareviewofbooks",
        "bomb-painting",
        "artforum",
        "artreview",
        "brooklyn-rail",
        "spike",
        "frieze",
        "eflux",
        "tripleampersand",
        "texte-zur-kunst",
        "grey-room",
        "triplecanopy",
        "draught",
        "interlude-docs",
        "future-feed",
        "ambient-receiver",
        "emergence",
        "dis-art",
        "greatbritishchefs",
        "greatitalianchefs",
        "serious-eats",
        "ottolenghi",
        "rachel-eats",
        "david-lebovitz",
        "the-kitchn",
        "the-guardian",
        "saveur",
        "brindisa"
      ]
    },
    {
      "label": "p o l i t i c s",
      "items": [
        "novara",
        "damage",
        "dissent",
        "counterpunch",
        "nlr-sidecar",
        "the-canary",
        "anarchist-library"
      ]
    },
    {
      "label": "m u s i c",
      "items": [
        "the-quietus",
        "the-wire"
      ]
    },
    {
      "label": "p o e t r y",
      "items": [
        "spam",
        "poetry-foundation",
        "jacket2",
        "asymptote",
        "blackbox-manifold",
        "free-trials",
        "blush",
        "erotoplasty",
        "tentacular-mag",
        "dirt-children",
        "diagram",
        "datableed",
        "permeable-barrier",
        "shitwonder"
      ]
    },
    {
      "label": "l i b r a r i e s",
      "items": [
        "electronic-poetry-centre",
        "annas-archive",
        "monoskop"
      ]
    },
    {
      "label": "p h y s i c a l",
      "items": [
        "bftk",
        "slub-press",
        "good-press",
        "rile-books"
      ]
    }
  ],
  "advancedGroups": [
    "Art/Theory",
    "Lit/Essay",
    "Ecology",
    "Poetry",
    "Music",
    "Food",
    "Politics"
  ],
  "sites": {
    "eflux": {
      "label": "e-flux",
      "url": "https://www.e-flux.com/journal",
      "domain": "e-flux.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "theory"
      ]
    },
    "artforum": {
      "label": "art forum",
      "url": "https://artforum.com",
      "domain": "artforum.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "criticism"
      ]
    },
    "artreview": {
      "label": "art review",
      "url": "https://artreview.com",
      "domain": "artreview.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "criticism"
      ]
    },
    "spike": {
      "label": "spike",
      "url": "https://spikeartmagazine.com",
      "domain": "spikeartmagazine.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "criticism"
      ]
    },
    "grey-room": {
      "label": "grey room",
      "url": "https://www.greyroom.org",
      "domain": "greyroom.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "theory",
        "academia"
      ]
    },
    "brooklyn-rail": {
      "label": "brooklyn rail",
      "url": "https://brooklynrail.org",
      "domain": "brooklynrail.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "criticism"
      ]
    },
    "tank": {
      "label": "tank",
      "url": "https://tank.tv/magazine",
      "domain": "tank.tv",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "art",
        "culture"
      ]
    },
    "the-baffler": {
      "label": "the baffler",
      "url": "https://thebaffler.com/latest",
      "domain": "thebaffler.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "politics",
        "criticism"
      ]
    },
    "granta": {
      "label": "granta",
      "url": "https://granta.com",
      "domain": "granta.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "literary"
      ]
    },
    "white-review": {
      "label": "the white review",
      "url": "https://thewhitereview.org",
      "domain": "thewhitereview.org",
      "onHomepage": false,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "literary",
        "criticism"
      ]
    },
    "stinging-fly": {
      "label": "the stinging fly",
      "url": "https://stingingfly.org",
      "domain": "stingingfly.org",
      "onHomepage": false,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "literary"
      ]
    },
    "the-drift": {
      "label": "the drift",
      "url": "https://thedriftmag.com",
      "domain": "thedriftmag.com",
      "onHomepage": false,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "politics",
        "literary"
      ]
    },
    "spam": {
      "label": "SPAM",
      "url": "https://www.spamzine.co.uk/",
      "domain": "spamzine.co.uk",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay",
        "Poetry"
      ],
      "tags": [
        "literary",
        "poetry"
      ]
    },
    "diagram": {
      "label": "diagram",
      "url": "https://thediagram.com/",
      "domain": "thediagram.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Poetry"
      ],
      "tags": [
        "poetry",
        "weird"
      ]
    },
    "blackbox-manifold": {
      "label": "blackbox manifold",
      "url": "https://blackboxmanifold.sites.sheffield.ac.uk/",
      "domain": "blackboxmanifold.sites.sheffield.ac.uk",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Poetry"
      ],
      "tags": [
        "poetry",
        "theory"
      ]
    },
    "ambient-receiver": {
      "label": "ambient receiver",
      "url": "https://www.ambientreceiver.org/contents",
      "domain": "ambientreceiver.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Ecology"
      ],
      "tags": [
        "sound",
        "ecology"
      ]
    },
    "emergence": {
      "label": "emergence",
      "url": "https://emergencemagazine.org",
      "domain": "emergencemagazine.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Ecology"
      ],
      "tags": [
        "ecology",
        "culture"
      ]
    },
    "spam-plaza": {
      "label": "SPAM plaza",
      "url": "https://www.spamzine.co.uk/plaza",
      "domain": "spamzine.co.uk",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "nplusone": {
      "label": "n+1",
      "url": "https://nplusonemag.com",
      "domain": "nplusonemag.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": []
    },
    "draught": {
      "label": "draught",
      "url": "https://draughtjournal.com",
      "domain": "draughtjournal.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "lrb-blog": {
      "label": "lrb blog",
      "url": "https://www.lrb.co.uk/blog/",
      "domain": "lrb.co.uk",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "lareviewofbooks": {
      "label": "los angeles review of books",
      "url": "https://lareviewofbooks.org",
      "domain": "lareviewofbooks.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "bomb-painting": {
      "label": "bomb",
      "url": "https://bombmagazine.org/",
      "domain": "bombmagazine.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": []
    },
    "frieze": {
      "label": "frieze",
      "url": "https://www.frieze.com",
      "domain": "frieze.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "future-feed": {
      "label": "future feed",
      "url": "https://future-feed.net/",
      "domain": "future-feed.net",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "dis-art": {
      "label": "dis.art",
      "url": "https://dis.art",
      "domain": "dis.art",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "interlude-docs": {
      "label": "interlude docs",
      "url": "https://interludedocs.com",
      "domain": "interludedocs.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "damage": {
      "label": "damage",
      "url": "https://damagemag.com",
      "domain": "damagemag.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "nlr-sidecar": {
      "label": "nlr sidecar",
      "url": "https://newleftreview.org/sidecar",
      "domain": "newleftreview.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "novara": {
      "label": "novara",
      "url": "https://novaramedia.com/",
      "domain": "novaramedia.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "dissent": {
      "label": "dissent",
      "url": "https://www.dissentmagazine.org/",
      "domain": "dissentmagazine.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "the-canary": {
      "label": "the canary",
      "url": "https://www.thecanary.co",
      "domain": "thecanary.co",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "the-quietus": {
      "label": "the quietus",
      "url": "https://thequietus.com",
      "domain": "thequietus.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Music"
      ],
      "tags": []
    },
    "the-wire": {
      "label": "the wire",
      "url": "https://www.thewire.co.uk",
      "domain": "thewire.co.uk",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Music"
      ],
      "tags": []
    },
    "jacket2": {
      "label": "jacket2",
      "url": "https://jacket2.org",
      "domain": "jacket2.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "free-trials": {
      "label": "free trials",
      "url": "https://pxxtry.com/",
      "domain": "pxxtry.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "blush": {
      "label": "blush",
      "url": "https://www.blush-lit.com/",
      "domain": "blush-lit.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "erotoplasty": {
      "label": "erotoplasty",
      "url": "https://erotoplasty.tumblr.com/",
      "domain": "erotoplasty.tumblr.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "slub-press": {
      "label": "slub press",
      "url": "https://slubpress.cargo.site/",
      "domain": "slubpress.cargo.site",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "tentacular-mag": {
      "label": "tentacular mag",
      "url": "https://www.tentacularmag.com/",
      "domain": "tentacularmag.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "dirt-children": {
      "label": "dirt children",
      "url": "https://dirtchildren.com/journal/",
      "domain": "dirtchildren.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "datableed": {
      "label": "datableed",
      "url": "https://www.datableedzine.com/",
      "domain": "datableedzine.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "permeable-barrier": {
      "label": "permeable barrier",
      "url": "https://www.permeablebarrier.com/lurking",
      "domain": "permeablebarrier.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "shitwonder": {
      "label": "shitwonder",
      "url": "https://wonder-publishing.com/shitwonder",
      "domain": "wonder-publishing.com",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "electronic-poetry-centre": {
      "label": "electronic poetry centre",
      "url": "https://writing.upenn.edu/epc/library/",
      "domain": "writing.upenn.edu",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "annas-archive": {
      "label": "anna's archive",
      "url": "https://annas-archive.org/",
      "domain": "annas-archive.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "monoskop": {
      "label": "monoskop",
      "url": "https://monoskop.org/",
      "domain": "monoskop.org",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "lrb": {
      "label": "london review of books",
      "url": "https://www.lrb.co.uk/",
      "domain": "lrb.co.uk",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": []
    },
    "tripleampersand": {
      "label": "&&&",
      "url": "https://tripleampersand.org/",
      "domain": "https://tripleampersand.org/",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": [
        "criticism",
        "theory"
      ]
    },
    "texte-zur-kunst": {
      "label": "texte zur kunst",
      "url": "https://www.textezurkunst.de/en/",
      "domain": "textezurkunst.de",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Art/Theory"
      ],
      "tags": []
    },
    "triplecanopy": {
      "label": "triple canopy",
      "url": "https://canopycanopycanopy.com/",
      "domain": "canopycanopycanopy.com/",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "art",
        "culture",
        "ecology",
        "criticism"
      ]
    },
    "rile-books": {
      "label": "rile books",
      "url": "https://rile.space/",
      "domain": "rile.space/",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "good-press": {
      "label": "good press",
      "url": "https://goodpress.co.uk/pages/shop",
      "domain": "goodpress.co.uk/pages/shop",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "bftk": {
      "label": "bricks from the kiln",
      "url": "https://www.b-f-t-k.info/",
      "domain": "www.b-f-t-k.info/",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": false,
      "defaultAdvanced": false,
      "advancedGroups": [],
      "tags": []
    },
    "cabinet": {
      "label": "cabinet",
      "url": "https://cabinetmagazine.org",
      "domain": "cabinetmagazine.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Lit/Essay"
      ],
      "tags": [
        "criticism",
        "literary"
      ]
    },
    "asymptote": {
      "label": "asymptote",
      "url": "https://asymptotejournal.com",
      "domain": "asymptotejournal.com",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Poetry"
      ],
      "tags": [
        "poetry",
        "criticism"
      ]
    },
    "poetry-foundation": {
      "label": "poetry foundation",
      "url": "https://www.poetryfoundation.org",
      "domain": "poetryfoundation.org",
      "onHomepage": true,
      "inQuickSearch": true,
      "inAdvancedSearch": true,
      "defaultAdvanced": true,
      "advancedGroups": [
        "Poetry"
      ],
      "tags": [
        "poetry",
        "criticism"
      ]
    },
    "greatbritishchefs": {
      "label": "greatbritishchefs",
      "url": "greatbritishchefs.com",
      "domain": "greatbritishchefs.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "greatitalianchefs": {
      "label": "greatitalianchefs",
      "url": "greatitalianchefs.com",
      "domain": "greatitalianchefs.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "serious-eats": {
      "label": "serious-eats",
      "url": "seriouseats.com",
      "domain": "seriouseats.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "ottolenghi": {
      "label": "ottolenghi",
      "url": "ottolenghi.co.uk",
      "domain": "ottolenghi.co.uk",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "rachel-eats": {
      "label": "rachel-eats",
      "url": "https://racheleats.wordpress.com/",
      "domain": "racheleats.wordpress.com/",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "david-lebovitz": {
      "label": "david-lebovitz",
      "url": "https://www.davidlebovitz.com/",
      "domain": "www.davidlebovitz.com/",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "the-kitchn": {
      "label": "the-kitchn",
      "url": "thekitchn.com",
      "domain": "thekitchn.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "the-guardian": {
      "label": "the-guardian",
      "url": "theguardian.com",
      "domain": "theguardian.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "counterpunch": {
      "label": "counterpunch",
      "url": "https://www.counterpunch.org/",
      "domain": "counterpunch.org/",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "anarchist-library": {
      "label": "anarchist-library",
      "url": "https://theanarchistlibrary.org/special/index",
      "domain": "theanarchistlibrary.org/special/index",
      "onHomepage": true,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Politics"
      ],
      "tags": []
    },
    "saveur": {
      "label": "saveur",
      "url": "saveur.com",
      "domain": "saveur.com",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    },
    "brindisa": {
      "label": "brindisa",
      "url": "https://brindisa.com/blogs/spanish-food-recipes",
      "domain": "brindisa.com/blogs/spanish-food-recipes",
      "onHomepage": false,
      "inQuickSearch": false,
      "inAdvancedSearch": true,
      "defaultAdvanced": false,
      "advancedGroups": [
        "Food"
      ],
      "tags": []
    }
  }
};
